SELECT a.ID, a.SCANUSERID, a.OCID, a.WORKERID, a.CARRIERID, a.FIELDID, a.TASKNO, 
       a.RIPEBCH, a.UNRIPEBCH, a.BLACKBCH, a.ROTTENBCH, a.LONGSTALKBCH, a.RATDMGBCH, 
       a.LOOSEFRUIT, a.TRANSNO, a.TRANSDATE, a.TRANSTIME, a.UPLOADDATETIME, 
       a.RECORDTAG, a.TRANSSTATUS, a.TRANSTYPE, a.LASTUSER, a.LASTUPDATED, 
       a.OVERRIPEBCH, a.UNDERRIPEBCH, a.ABNORMALBCH, a.LOOSEFRUIT2
FROM FFBSCANNERDATA04 a
WHERE a.TRANSDATE >= '2025-03-01' AND a.TRANSDATE < '2025-04-01'
AND a.TRANSNO IN (
    SELECT TRANSNO
    FROM FFBSCANNERDATA04
    WHERE TRANSDATE >= '2025-03-01' AND TRANSDATE < '2025-04-01'
    GROUP BY TRANSNO
    HAVING COUNT(*) > 1
)
ORDER BY a.TRANSNO, a.TRANSDATE;